### ISSUE TITLE
Switch to use `http-errors` instead?

### ISSUE THREAD

**Issue by tunnckoCore** [vercel/micro#128]
It won't be kind of breaking change. It has same signature and more "features" - more used and it is everywhere in koa/express/connect. ;] So I think it would be better for users to be some that they already know.

**Comment by onbjerg** [comment]
The default error handler is deprecated, and as such it is up to the user to implement error handling themelves.

You could write a small library that does this, but I don't think it should be in the core, as it doesn't match the new direction of micro.

I made an example of a custom error wrapper using [Boom](https://github.com/hapijs/boom): https://github.com/onbjerg/micro-boom

**Comment by tunnckoCore** [comment]
I more thought for the internal errors, but yea not make sense.

edit: as about micro-boom, why include `async-to-gen` in deps?

**Comment by onbjerg** [comment]
@tunnckoCore It is because I was under the impression that it was needed by ``ava`` for await/async functionality, but I can see it is supported directly out of the box.

I guess it should be a dev dependency then, since I still use it to transpile for await/async functionality.

Good catch, thanks! 😊

**Comment by tunnckoCore** [comment]
Yea, in any way it should be as devDep :)
