### ISSUE TITLE
Multiple micro services communicating with the same database - bad practice?

### ISSUE THREAD

**Issue by nickredmark** [vercel/micro#138]
The design of micro sems to favor a multitude of independent micro services.
Would you go as far as having multiple micro services talking to the same database?

**Comment by timneutkens** [comment]
It's really a matter of preference and how far you want to go when separate services. Say you want to create an api endpoint for products, you could create one `micro` service that handles all CRUD operations, or a separate service for each. In that case it would be perfectly fine for them to talk to the same database. Because they all work on the same data.

I'm not sure how ZEIT handles it. But this seems like a good article about microservices in general:
https://arstechnica.com/information-technology/2016/05/blow-that-data-monolith-to-smithereens-with-microservices-and-database-swarms/

**Comment by daru23** [comment]
Theoretically each micro service should have it owns database, is one of the principal to recognise if can stand alone as a micro service, it should run by itself, be independent. If you have several micro services using the same database could cause conflicts writing and reading, beside another conflicts.

**Comment by timneutkens** [comment]
@nmaro I guess this answers your question 😄 Feel free to re-open if it doesn't.
