### ISSUE TITLE
Should we add a raw text method?

### ISSUE THREAD

**Issue by timneutkens** [vercel/micro#174]
See #118

**Comment by leo** [comment]
Please do [this](https://github.com/zeit/micro/pull/118#issuecomment-270204610), if you have time.

**Comment by floatdrop** [comment]
@leo can you elaborate on this? `.text` method will not introduce new dependencies (because `raw-body` is used for `.json` already) and will do nice decomposition of `.json` method. Seems logical to expose such method, if `mirco` already have this code inside.

Also I think #207 caused by confusing `.json` method with parsing plain bodies.

**Comment by leo** [comment]
Resolved with https://github.com/zeit/micro/pull/208
