### ISSUE TITLE
"Orchestrating microservices" tutorial or sample project 

### ISSUE THREAD

**Issue by Obiwarn** [vercel/micro#306]
As a beginner, right now I am a bit lost how to "glue everything together".

A bigger example project answering the following would be great:
- Can I just use now services (Path Alias, Secrets, etc.) to create a complete application based on microservices. Or do I need anything more (see next question)?
- What third party tools do you recommend / use? As a beginner I find Nginx, JHipster, Amalgam8, Linker-D, etc. Do I need any of these?
- How should two microservices communicate? Just call fetch()? 
- How to use JWT? How to share a signing secret? 
- How to use path alias rules? (https://zeit.co/docs/features/path-aliases)
- What is the recommended folder structure for a project containing multiple microservices? (e.g. where to put the secrets, build scripts, rules.json)

**Comment by snewell92** [comment]
I'd like some guidance to cluster. There's the micro-cluster package, but I'm not entirely sure if I should just use pm2's clustering... or perhaps not use micro-cluster and just make my micro service use docker, then I can use docker swarm...? (They're probably all valid I guess)

**Comment by paulogdm** [comment]
Yes to that please!

**Comment by paulogdm** [comment]
Update: Each micro service is now alone in his own git repo. My "main repo" just uses one "rules.json" and holds the DOCs and a few scripts. If you use `now`, this is the way to go, but if you don't, you are on your own here...
It seems that Zeit's wants us to use his idea of how to deploy an application and if you don't want to, well you have the source code and a bunch of other options out there... It is indeed not a job of `micro` to show you how to glue two running servers, because that is a specific problem that depends on the deploy platform.

**Comment by snuggs** [comment]
@tmornini @brandondees great discussion on microservice architectures. some questions i've had myself.

@obiwarn #FunFact At minimum `fetch` is all the "Bus stops" you need. Although many feel the need for added complexity as a security blanket. YMMV.

**Comment by timneutkens** [comment]
Now 2.0 solves a lot of the questions you have/had: https://zeit.co/blog/now-2
