### ISSUE TITLE
socket.io example is not working with now

### ISSUE THREAD

**Issue by ybbarng** [vercel/micro#377]
Hello,

I tried deploying your [socket.io example](https://github.com/zeit/micro/tree/master/examples/socket.io-chat-app) with now but it looks like doesn't working.

The console log of [my instance](https://socketio-chat-app-ccuraebd4.now.sh/) says 404 on getting resources from `/socket.io/`.

Is there anything that I missed to configure to make it work?

**Comment by timneutkens** [comment]
Since Now 2.0 currently doesn't support websockets I'm going to close this issue.
https://zeit.co/blog/now-2

**Comment by ybbarng** [comment]
Then it will be better to remove the not-working example or some note is added to make it not confusing.

**Comment by corysimmons** [comment]
@timneutkens Since Next API Routes are based on micro (I think?) then does this mean there is no hope of API Routes/Now 2.0, doing any WebSocket stuff? Specifically important for GraphQL Subscriptions...

Do we just make a [custom Express server](https://nextjs.org/docs/advanced-features/custom-server) and host somewhere else?

**Comment by timneutkens** [comment]
> Next API Routes are based on micro

They're not, it's a different implementation.

> does this mean there is no hope of API Routes/Now 2.0, doing any WebSocket stuff?

Vercel.com does not currently support websockets, we recommend using a reliable queuing system instead like https://pusher.com/
